### ISSUE TITLE
extension fails on startup, works after toggling off and on in about:addons

### ISSUE THREAD

**Issue by korakinos** [browserpass/browserpass-extension#253] opened 2021-01-15 17:02 UTC
### General information

-   Operating system + version: 
 **Regolith (based on Ubuntu 20.04.1 LTS)**
-   Browser + version: 
 **Firefox 84.0.2**
-   Information about the host app:
    -   How did you install it? 
     **Package manager (apt)**
    -   If installed an official release, put a version 
```
$ apt-cache show webext-browserpass | grep Version
Version: 3.4.1-3
```
-   Information about the browser extension:
    -   How did you install it?
        ~~**From within Firefox from addons.mozilla.org.**~~
        (edit: sorry, this was a mistake, installed via apt with the package webext-browserpass)
    -   Browserpass extension version as reported by your browser: 
     **3.4.1**

---

### Exact steps to reproduce the problem

1. Install and configure browserpass extension and host app.

2. Close and restart Firefox.

### What should happen?

The Browserpass icon should show up in the bar, the shortcuts (Ctrl-Shift-F, Ctrl-Shift-L) should work.

### What happened instead?

The Browserpass icon doesn't show up on startup of Firefox. The shortcuts don't work. 

The extension is listed as active in `about:addons`, and it is listed under **about:debugging#/runtime/this-firefox**. When clicking to debug it there, I get an error page detailing `TypeError: target is null`.

Disabling and re-enabling the extension in `about:addons` restores the icon, the shortcuts and (it appears) all functionality.

**Comment by maximbaz** [comment] 2021-01-15 19:51
Hey, thanks for reaching out. Sadly I am unable to reproduce, on the exact same Firefox version.

Could you please try in a fresh profile?

```
PROFILEDIR=$(mktemp -p /tmp -d tmp-fx-profile.XXXXXX.d)
/path/to/firefox -profile "$PROFILEDIR" -no-remote -new-instance
```

**Comment by korakinos** [comment] 2021-01-20 08:44
Sure thing, I just did. (Thanks for the handy shell snippet. And sorry for replying so late, somehow I didn't see your reply before, I think my Firefox is overzealous in caching Github issue pages.)

In a fresh profile the error is slightly different: The icon of the extension appears, but when I click on it or press Ctrl-L, the popup displays the message "`TypeError: URL constructor: null is not a valid URL.`" instead of the usual content of the extension.

**Comment by erayd** [comment] 2021-01-20 09:14
Could you please double-check which version of Browserpass you have installed in your browser? I just noticed that the version reported on your original post is significantly out of date - that version is over a year old. If you've reported it correctly, something is broken with your browser's ability to automatically update extensions.

**Comment by erayd** [comment] 2021-01-20 09:16
Also, that host version isn't right either. The current host version is 3.0.7; the version you've reported in your post doesn't even exist.

**Comment by korakinos** [comment] 2021-01-20 09:53
Ah, I see! I was obviously mistaken about having installed the extension from addons.moziilla.org. It appears the ubuntu package `webext-browserpass` pulled in both the host and the extension (and both in old versions, which I just double-checked; weird that one shouldn't even exist).

After installing the extension from addons.mozilla.org instead, the bug I had reported is no longer present. (I yet have to to install the host program in another way than via the `ebext-browserpass` package. I hope to do so later today or tomorrow.)

I really should have my setup checked better before reporting. Sorry, and hank you for your time and effort!

**Comment by erayd** [comment] 2021-01-20 10:00
Great to hear you have it sorted!

@maximbaz Do you know who does the Ubuntu packages? Bit concerning they are still shipping things that far out of date.

**Comment by maximbaz** [comment] 2021-01-20 10:07
@meskes, a friendly ping 👋 🙂 

I can see the package [is already flagged as out-of-date](https://tracker.debian.org/pkg/browserpass), we should consider removing the link to Debian package from README until it's up-to-date again 🤔

**Comment by maximbaz** [comment] 2021-01-20 10:40
Instead of removing the link, I added a note that the package is not to be used because it's significantly outdated. 
Let's close the issue and revisit if we hear that Debian package is up-to-date again 😉

**Closed by maximbaz** 2021-01-20 10:40 UTC

**Comment by erayd** [comment] 2021-01-20 10:46
Perfect 😁.

**Comment by meskes** [comment] 2021-01-20 12:21
> I can see the package is already flagged as out-of-date, we should
> consider removing the link to Debian package from README until it's
> up-to-date again 

I'd love to see the package updated but I'm currently very short of
spare time. Any help would be appreciated.

Michael
-- 
Michael Meskes
Michael at Fam-Meskes dot De
Michael at Meskes dot (De|Com|Net|Org)
Meskes at (Debian|Postgresql) dot Org

**Comment by meskes** [comment] 2021-01-20 12:24
FWIW I doubt this issue relates to browserpass at all. *All* extensions
installed through Debian/Ubuntu packages show the same behavior in
firefox. Disabling/re-enabling helps as does killing and restarting
firefox. My guess is that the way the extensions are side-loaded causes
this issue.

Michael
-- 
Michael Meskes
Michael at Fam-Meskes dot De
Michael at Meskes dot (De|Com|Net|Org)
Meskes at (Debian|Postgresql) dot Org
