### ISSUE TITLE
How to use modal HTTP auth (usage via shortcuts)

### ISSUE THREAD

**Issue by flyinggreenfrog** [browserpass/browserpass-extension#177] opened 2019-09-28 12:34 UTC
For using modal HTTP auth with Firefox according to https://github.com/browserpass/browserpass-extension#available-keyboard-shortcuts it has to be used via shortcuts (ctrl+G or ctrl+shift+G).

But ctrl+G and ctrl+shift+G are already used from firefox for search tasks (https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly).

I updated to Firefox 69 to be able to change shortcuts for extensions, but when I go to the shortcuts settings for browserpass I only could change ctrl+shift+L and ctrl+shift+F shortcuts.

So my issue at the moment is how to use browsepass extension to open URL with basic HTTP auth, ctrl+G and ctrl+shift+G is opening the firefox search, or does nothing when used on an browserpass entry.

**Comment by maximbaz** [comment] 2019-09-28 21:29
Hey!

This isn't really an issue, because contrary to `Ctrl+Shift+L/F`, these `Ctrl+G`/`Ctrl+Shift+G` shortcuts are not global, they are local to a specific popup entry. I've just tested on Firefox 69.0.1, they do work as expected, they don't conflict with Firefox search shortcuts.

I think perhaps here's what was not clear for you: `Ctrl+G` is not meant to be pressed to open a popup, you first should open it with `Ctrl+Shift+L`, then you search for the website that you want to open (say in the current tab), make sure it is the first entry in the popup OR is focused with arrow keys, and then you press `Ctrl+G` to open it.

Please give it a try and let me know if this doesn't work!

**Comment by flyinggreenfrog** [comment] 2019-09-28 22:01
Hi.

Thanks for your explanations. After playing around (temporarily disabling) with my other used firefox plugins, I got it working (but not with my keyboard layout, since I use Neo2). Since with normal either en or de keyboard layout, it is working according to your explanations, this issue for me (never was for the plugin) is not in this plugin, but in my combination of using Neo2 keyboard layout.

Do you see a chance how to debug this or give me a hint, if there is any possibility to see for a firefox plugin, which keyboard strokes it receives after your plugin was opened on an pass entry with a "url: <URL>" line?

**Comment by maximbaz** [comment] 2019-09-28 22:08
Let's try something simple first, open [this website](https://unixpapa.com/js/testkey.html), activate "classic" + "modifiers" on "keypress" and then press `Ctrl+G`, what do you see?

https://unixpapa.com/js/testkey.html

![image](https://user-images.githubusercontent.com/1177900/65822953-26091780-e24d-11e9-947c-85c027a7258b.png)

**Comment by flyinggreenfrog** [comment] 2019-09-28 22:22
With my Neo2 layout I have the following (which looks for me the same as your output):

![20190929_001536](https://user-images.githubusercontent.com/4796558/65823042-24405380-e24f-11e9-8aaf-f172b2ddbfb4.png)

**Comment by maximbaz** [comment] 2019-09-28 22:35
> EDIT: Sometimes I get ctrlKey=false sometimes ctrlKey=true for pressing ctrl. I tried both left and right ctrl key.

This could be the root cause, if `ctrl` is not registered, Browserpass will ignore this keypress.

But here's how to debug the extension itself:

1. Go to about:debugging#/runtime/this-firefox
1. Click Inspect next to Browserpass

    ![image](https://user-images.githubusercontent.com/1177900/65823115-8a79a600-e250-11e9-823a-5a7d0bcfcded.png)

1. In there find `popup.dist.js` and search for "KeyG":

    ![image](https://user-images.githubusercontent.com/1177900/65823118-9a918580-e250-11e9-92fd-39a446aac2a5.png)

1. Put the breakpoint to where I have it on the screenshot above, and then in the popup focus any entry with arrow key (make sure the focus is on an entry, not in search box), and hit `Ctrl+G`.

Hopefully you will get stopped on a breakpoint and then you can hover and see what is the value of `e.ctrlKey`.

**Comment by maximbaz** [comment] 2019-09-29 18:30
I'll close the issue as there's nothing to change in extension code, but I do encourage you to get to the bottom of it, and feel free to post here the results or further questions, I'll be happy to assist 🙂

**Closed by maximbaz** 2019-09-29 18:30 UTC
