### ISSUE TITLE
Add ability to turn off badge on icon

### ISSUE THREAD

**Issue by anna-is-cute** [browserpass/browserpass-extension#103] opened 2019-04-14 01:33 UTC
### General information

-   Operating system + version: Ubuntu 18.10
-   Browser + version: Firefox Nightly 68.0a1 (2019-04-08) (64-bit)
-   Information about the host app:
    -   How did you install it? pre-built binary
    -   If installed an official release, put a version `Browserpass host app version: 3.0.6`
-   Information about the browser extension:
    -   How did you install it? AMO
    -   Browserpass extension version as reported by your browser: 3.0.9

### Exact steps to reproduce the problem

1. Install the extension

2. Open a domain with saved passwords

### What should happen?

The ability to turn off the icon badge should exist.

![image](https://user-images.githubusercontent.com/955250/56087162-d082af00-5e54-11e9-9e1f-800e049ebbd4.png)

The first thing I do is turn this off on any extension.

### What happened instead?

It doesn't or is buried somewhere hard to find.

**Comment by erayd** [comment] 2019-04-14 01:43
@jkcclemens Thanks for your issue report.

Are you able to explain your reasoning in a bit more detail? I'm open to considering it, but that also needs to be balanced against a desire to keep the options screen simple. If we can better understand why you would want to do this, then we can make a properly informed decision.

**Comment by jkcclemens** [comment] 2019-04-14 02:09
It's inconsistent design with the rest of my browser. The rest of the icons that I keep visible because they're useful have options to turn this off, and I have. 

![image](https://user-images.githubusercontent.com/955250/56087355-1fcade80-5e59-11e9-84da-4faaafdf61bc.png)

Also, it just looks ugly to me.

Aesthetics aside, I gain nothing from the number functionally. I know what sites I have accounts on. If I didn't, I wouldn't be interested in the *number* of accounts, only if I *had* one, which could be represented by icon colour (which I would also want to be able to turn off).

It also obscures the icon and makes it harder for me to immediately recognise.

Really, though, there's no reason not to add this option. For what it's worth, literally every other addon I have installed with a badge has the option to turn it off.

---

CanvasBlocker
![image](https://user-images.githubusercontent.com/955250/56087374-923bbe80-5e59-11e9-8e4d-5388db7b5a12.png)
uBlock Origin
![image](https://user-images.githubusercontent.com/955250/56087381-a41d6180-5e59-11e9-9760-26f9da6d32a2.png)
Stylus
![image](https://user-images.githubusercontent.com/955250/56087389-c31bf380-5e59-11e9-819d-abd7288a8844.png)
HTTPS Everywhere
![image](https://user-images.githubusercontent.com/955250/56087391-d202a600-5e59-11e9-8038-c862401681ca.png)
Privacy Badger
![image](https://user-images.githubusercontent.com/955250/56087394-dfb82b80-5e59-11e9-8c0c-d8d190ccbc32.png)
Decentraleyes
![image](https://user-images.githubusercontent.com/955250/56087397-ea72c080-5e59-11e9-84dc-0a23fbb62ebb.png)

**Comment by erayd** [comment] 2019-04-14 02:32
Thanks - that all makes sense.

@maximbaz - do you have a strong opinion either way on this? I'm personally happy for us to add this option.

**Comment by maximbaz** [comment] 2019-04-14 08:20
Hey, thanks for the feedback! 

To be honest, I'm not sold on this yet, I'd rather see this energy put into lobbying Firefox to improve their design of the badge icon than asking every single extension to provide a new option. For example in Chromium the badge is smaller and positioned in a way that doesn't obscure icons, looks quite good IMHO.

> Aesthetics aside, I gain nothing from the number functionally. I know what sites I have accounts on. I know what sites I have accounts on. If I didn't, I wouldn't be interested in the number of accounts, only if I had one, which could be represented by icon colour (which I would also want to be able to turn off).

We can also argue that a presence of badge _is_ our indication of whether you have an account or not, only it's multi-functional and in addition it shows a number of matches to those who need it.

There are valid scenarios to want this functionality, for example if you know that you have two accounts on a current website, but see `3` or no badge at all, this should trigger a suspicion in you to double-check the current domain, in case you are being a victim of a phishing attack right now.

> Really, though, there's no reason not to add this option. For what it's worth, literally every other addon I have installed with a badge has the option to turn it off.

I treat options with great care, in my opinion we shouldn't be adding new options unless there are _very_ good reasons to do so. Every single option that we have right now was carefully considered, and that's how we managed to keep the options simple, I think we should consider this trend. (Also, after the OTP thread I became quite immune to the arguments like "everyone is jumping from a cliff, so we should make it possible too" 😝)

I'm open to leave this issue open, see the number of upvotes and hear additional feedback, but I propose to not do this for now. If you file a bug for browser to improve the design of the badge, feel free to post a link here.

**Comment by erayd** [comment] 2019-04-14 12:09
@jkcclemens We decided to do it, but it won't be merged until after I've redone the options screen layout / CSS. If you're interested in trying it out in the meantime, you can install from the PR branch of #105.

**Comment by jkcclemens** [comment] 2019-04-14 15:31
Glad to see it was decided to be done.

@maximbaz

>I'd rather see this energy put into lobbying Firefox to improve their design of the badge icon than asking every single extension to provide a new option.

This would be great, but also you would have been actively hurting my experience because you think it should be Firefox, not the extension authors, who should control this. That is not reality (though I agree it would be great if it was), and it would be nice to provide this option until it becomes reality, which it looks like you will be doing!

>(Also, after the OTP thread I became quite immune to the arguments like "everyone is jumping from a cliff, so we should make it possible too" stuck_out_tongue_closed_eyes)

If everyone's doing it, I think it warrants a consideration of why they are. In this case, it's because it's a good idea to let users turn off a UI element that they don't want.

Thanks, @erayd, I'll try out the PR branch and look for any potential issues. :)

**Comment by maximbaz** [comment] 2019-04-14 15:38
Yep, we talked a lot about this offline (so it wasn't a rushed decision) and concluded that this request together with the "light theme" would be reasonable configurations to provide for a user interface. Enjoy 🙂

**Comment by mcnesium** [comment] 2019-04-17 08:59
Thumbs up everyone :)

Though this is solved already, I would like to add an argument for this option: as a friend of explaining problems through providing a screenshot, I often do so with the entire browser window (e.g. because the current URL is important, or whatever). In this case I would either have to temporarily remove the icon first, or otherwise expose the number of accounts I have on this site to the public. This sounds like being a theoretical problem and in 99% it propably is, but there could be this one incident where an information like this leads to the world imploding (see [Butterfly effect](https://en.wikipedia.org/wiki/Butterfly_effect)). I am sure you wouldn't want to be guilty of this, just to keep the code simple, right? ;-)

Thank you everyone who's involved in this!

**Comment by DamienCassou** [comment] 2019-04-17 09:23
> I am sure you wouldn't want to be guilty of this, just to keep the code simple, right? ;-)

You made me laugh, thank you :-). To be fair with the maintainers though, I think keeping the code simple is not the only reason; keeping the preference UI simple is probably another good one in my opinion. I like the fact that Firefox has a simple preference UI and still gives full control through `about:config`. It would be cool that extensions could benefit from `about:config` too.

**Comment by jplitza** [comment] 2019-11-13 18:20
I would like to add another reason: Performance.
I use a password store with over a thousand passwords. The badge triggers a search in this store every time a page loads. This slowed down my whole browsing experience to the point of me wanting a new CPU, until I noticed that disabling browserpass solved the problems and increased each page load by at least 1 second.

(You could argue that search performance should be optimized instead, and sure enough I'd agree. But you can only optimize it so much, and the bade will always add delay.)

**Comment by maximbaz** [comment] 2019-11-13 18:47
Hi there 👋 Would you be able to share some details about your environment, by creating a separate issue and filling out the template? Not saying "no" to this request (that's why the issue is open!), but I'd _also_ like to optimize Browserpass, so that other people can enjoy fast browsing even with the badge enabled. It is also the same code path that fetches logins to count passwords for the badge and to draw a list of logins in the popup, so I assume opening popup is just as slow for you, and I'd like to improve that if I can.

**Comment by jplitza** [comment] 2019-11-13 19:49
@maximbaz Sure thing! #194

**Comment by ascclemens** [comment] 2021-08-05 21:31
Wow, I forgot about this issue since it's two years old! I've been running my own version of the extension to turn off the badge and completely forgot that I was doing that until I moved to a new computer. I see that #230 now exists to implement this feature, but it seems it's had no activity for about a year. Is there any word on this? I appreciate your work on this! :)

**Closed** 2024-12-17 10:20 UTC
Labels: feature request
