### ISSUE TITLE
Firefox + Windows: Error: Attempt to postMessage on disconnected port

### ISSUE THREAD

**Issue by mattdconnell** [browserpass/browserpass-extension#156] opened 2019-08-08 21:13 UTC
### General information

-   Operating system + version: Windows 10, 1809 build
-   Browser + version: Firefox 60.8.0 ESR
-   Information about the host app:
    -   How did you install it? Via the MSI installer on the releases page
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.6
-   Information about the browser extension:
    -   How did you install it? addons.mozilla.org
    -   Browserpass extension version as reported by your browser: 3.1.1

---

### Exact steps to reproduce the problem

1. Install native messaging host application

2. Install browser extension

3. Click browser extension button

### What should happen?

Should get a list of password store entries

### What happened instead?

`Error: Error: Attempt to postMessage on disconnected port`

(yes, it says 'Error' twice)

### Notes

I have the setup working via *Chrome*, on the same machine + user, same GPG key, same password store.  

On Linux machines, I have BP working with Firefox and Chrome, same GPG key and password store.

So: 

- Chrome + Windows = :heavy_check_mark: 
- Chrome + Linux = :heavy_check_mark:
- Firefox + Linux = :heavy_check_mark:

I only encounter difficulties with FF on Windows, it seems.

I've tried deleting and creating a new Firefox profile, as well as uninstalling/reinstalling both FF and BP native messenger.

How do I troubleshoot this further?

Thank you for your time!

**Comment by maximbaz** [comment] 2019-08-08 21:23
Hey, if you get an error immediately upon opening the popup, it means the browser isn't configured properly. You are using MSI file which [is supposed to](https://github.com/browserpass/browserpass-native/blob/faaa99feb4423739a3c176a5759f4d2fb038b12f/windows-setup.wxs#L21-L23) configure Firefox, but there is a [known issue](https://github.com/browserpass/browserpass-native/issues/65) that places configuration in a wrong location in the registry (see that thread for details). I bet this is the root cause of your issue, and if you manually configure Firefox in the registry, it will work just fine.

I don't use Windows myself, but if you would have time to investigate and possibly fix the MSI issue, I would really appreciate your help and gladly merge a PR! 😉 😉

Let me know if performing manual steps as described in https://github.com/browserpass/browserpass-native/issues/65 has solved your issue, and if you want to help with MSI, let's move the discussion there 😉

**Comment by mattdconnell** [comment] 2019-08-08 21:42
Thank you!  I had glanced over that issue but the name didn't stick in my head as being related.

> if you manually configure Firefox in the registry, it will work just fine.

I did this, by exporting the `NativeMessagingHosts` key, editing it to remove `WOW6432Node` from the path, and then importing the keys.  (I've attached the .reg file I used, for convenience, for anyone else who stumbles across this issue.)  Once I configured the path to my password store, all is working as expected.

> I don't use Windows myself, but if you would have time to investigate and possibly fix the MSI issue, I would really appreciate your help and gladly merge a PR!

Unfortunately I'm in the same boat as you.  I only need Windows on my work machine, and only some of the time (dual boot), and I have no experience with building for Windows platforms either.

I'll drop a comment on the other issue with something that I spotted though.

### .reg file contents

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts]

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts\com.github.browserpass.native]
@="C:\\Program Files\\Browserpass\\firefox-host.json"

```

**Comment by maximbaz** [comment] 2019-08-08 21:55
Awesome! Thanks for posting the workaround, I'll close this ticket and lets use the other one to track the actual fix.

**Closed by maximbaz** 2019-08-08 21:55 UTC
