### ISSUE TITLE
Can't install extension on ArchLinux

### ISSUE THREAD

**Issue by colinaaa** [browserpass/browserpass-extension#151] opened 2019-05-29 10:21 UTC
### General information

-   Operating system + version: ArchLinux 5.1.5
-   Browser + version: Chromium 74.0.3729.169 Arch Linux
-   Information about the host app:
    -   How did you install it? 
	by pacman
        
    -   If installed an official release, put a version (`$ browserpass --version`): Browserpass host app version: 

-   Information about the browser extension:
    -   How did you install it? 
	by pacman
        
    -   Browserpass extension version as reported by your browser: I can't see it in my browser.

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

No, but it is said that 

> If you installed a distro package above, you are done!

So I did nothing.
---

### Exact steps to reproduce the problem

1. I used to have browserpass native from pacman and Chromium extension from webstore. 

2. I found it can't work one day and I tried to delete the webstore version and install from pacman. But the extension does not come out as expected.

### What should happen?

It seems that all the things installing from pacman can be used out of the box. So the extension should be found in my browser.

### What happened instead?

Apparently, it does not appear.

Did I do something wrong?

**Comment by maximbaz** [comment] 2019-05-29 10:31
Can you confirm that you installed `browserpass-chromium` package?

**Comment by colinaaa** [comment] 2019-05-29 10:31
All these things can be found in my file system, but there are not any extension in my browser.
```bash
$ cat /usr/share/chromium/extensions/pjmbgaakjkbhpopmakjoedenlfdmcdgm.json  
{
    "external_crx": "/usr/lib/browserpass-chromium/browserpass-chromium-3.1.1.crx",
    "external_version": "3.1.1"
}

$ ls /usr/lib/browserpass-chromium/browserpass-chromium-3.1.1.crx 
browserpass-chromium-3.1.1.crx

$ cat /etc/chromium/native-messaging-hosts/com.github.browserpass.native.json 
{
    "name": "com.github.browserpass.native",
    "description": "Browserpass native component for the Chromium extension",
    "path": "/usr/bin/browserpass",
    "type": "stdio",
    "allowed_origins": [
        "chrome-extension://naepdomgkenhinolocfifgehidddafch/",
        "chrome-extension://pjmbgaakjkbhpopmakjoedenlfdmcdgm/",
        "chrome-extension://klfoddkbhleoaabpmiigbmpbjfljimgb/"
    ]
}
```

**Comment by maximbaz** [comment] 2019-05-29 10:37
try to drag-and-drop the crx file from /usr/lib/browserpass-chromium/ into chrome://extensions, will it help? 

is it the first time you install browserpass, or you played with it before and uninstalled it at some point? 

also try to run chromium with a new profile to make sure the problem is not with your own profile: 

chromium --user-data-dir /tmp/test1

**Comment by colinaaa** [comment] 2019-05-29 13:01
That works. Thanks.

However, need I re-dragging and re-dropping every time it updates?

**Comment by maximbaz** [comment] 2019-05-29 13:19
No I don't think so - make sure to ping me if that happens!

My best guess on what happened is that for some reason your Chromium profile blocked our extension, and by manually drag-n-dropp'ing it into chrome://extensions you told Chromium that you want to unblock it. Now it should keep working and auto-updating as expected.

Closing for now, enjoy your new extension 😉

**Closed by maximbaz** 2019-05-29 13:19 UTC
