### ISSUE TITLE
Cannot handle \ in filename

### ISSUE THREAD

**Issue by vollkorn1982** [browserpass/browserpass-extension#149] opened 2019-05-27 10:16 UTC
### General information

-   Operating system + version: Ubuntu 18.04
-   Browser + version: Firefox 67.0
-   Information about the host app:
    -   How did you install it? Downloaded a pre-built binary
    -   If installed an official release, put a version (`$ browserpass --version`): % browserpass-linux64 --version
Browserpass host app version: 3.0.6
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it? Installed from mozilla webstore
    -   Browserpass extension version as reported by your browser: 3.1.1

---

### Exact steps to reproduce the problem

1. Create an entry in your pass storage with a \ in the filename. Remember that you might need to use \\ to escape the filename. I used `dom\\user` for this example.

2. Try to open this entry through the add-on. You will receive an error message:
```
Error: Unable to fetch and parse login fields: Error: {"status":"error","code":24,"version":3000006,"params":{"action":"fetch","error":"open /home/user/.password-store/webpages/webpage.com/dom/user.gpg: no such file or directory","file":"webpages/webpage.com/dom/user.gpg","message":"Unable to decrypt the password file","storeId":"default","storeName":"pass","storePath":"/home/user/.password-store"}}
```
It looks like that the add-on is trying to fetch the file `dom/user` instead of `dom\\user`, but it displays the entry correctly in the pop-up. Just when clicking on it or pressing enter to actually fetch the password and insert it into the web form, this error pops up.

### What should happen?

I expect the browserpass-extension to read the correct file on the filesystem including the backward slash.

### What happened instead?

browserpass-extension tries to read a file with a forward slash in the place of the backward slash and rightly fails to do so.

**Comment by maximbaz** [comment] 2019-05-27 11:38
Hey, thanks for report. This is a conscious by-design limitation that allows us to have a simple support both Unix and Windows path separators, to avoid issues like https://github.com/browserpass/browserpass-legacy/issues/278.

In v3 the logic now resides inside the extension, which is OS-agnostic and I'd like to keep it that way.

Let me know if this makes sense, and rename the file to avoid `/` and `\` symbols in file names.

**Comment by vollkorn1982** [comment] 2019-05-27 12:51
I understand, but if it is a conscious decision not to support certain file names I would expect a proper error message explaining so and how to fix this problem (i.e. avoiding certain characters in file names and putting the username inside the file). Instead I get a user experience that feels a lot like different parsers yielding different results.

I added a `login:` line into my pass file and everything works as expected.

**Comment by maximbaz** [comment] 2019-05-27 14:03
> Instead I get a user experience that feels a lot like different parsers yielding different results.

The behavior should be consistent, I completely agree. Here's what I see:

![image](https://user-images.githubusercontent.com/1177900/58424546-ea402480-8097-11e9-978d-c02307911794.png)

This tells me that browserpass detected a file called "backslash" in a folder "github.com/name/with". At this point I can understand that something is not right, because the real folder name is "github.com" and the real file name is "name\with\backslash". So invoking this password entry is raising an error as expected.

If I saw the correct file path, like on a fake example below, then I agree invoking it shouldn't just lead to an error message:

![image](https://user-images.githubusercontent.com/1177900/58424784-7ce0c380-8098-11e9-97f8-8e43bfd3527f.png)

So, wrong file name in the popup is our indication that something is not right. I'll also put in README now that we aren't allowing `\` or `/` symbols in file names. Thanks again!

**Comment by maximbaz** [comment] 2019-05-27 14:11
https://github.com/browserpass/browserpass-extension/commit/5e31b0d4d5233d633b4d578eb96e0eb18ede37c2

**Comment by erayd** [comment] 2019-05-27 14:12
@maximbaz I do feel like this is a bug we need to fix though. The path provided by the host app should map to an actual file, and the extension should display it accordingly - anything else is our fault.

Using slashes in a filename is appallingly bad practice generally anyway, and users should not be doing it... but as it's technically possible, and we have a real-world example of a user who is doing exactly that, we should handle it.

**Comment by maximbaz** [comment] 2019-05-27 14:22
we've chatted some more, @erayd has an interesting idea of detecting real separator based on first character of the full path, so let's reopen to implement the proper fix. Remember to revert the commit above in the PR 😉

**Comment by maximbaz** [comment] 2019-09-27 14:18
I've looked again into this issue, and I'm tempted to propose again to close it as "by design" for the reasons below:

1. It is host app and not extension that is currently replacing `\` with `/` ([link](https://github.com/browserpass/browserpass-native/blob/faaa99feb4423739a3c176a5759f4d2fb038b12f/request/list.go#L78)), so any fix would involve releasing a new host app version and having to write extension code that can somehow work with both responses.
1. It was a conscious decision in v3 to try to "normalize" paths (i.e. treat both `\` and `/` as path separators and convert them to `/`) so that extension can behave and look similarly on Unix and Windows platforms (it wasn't like that in v2, and it was annoying)

I completely understand that it isn't ideal, but considering everything in this case I'm tending to prefer to sacrifice the perfection and continue claiming that `\` and `/` are intentionally not supported characters in file names, as we planned initially and documented in May in https://github.com/browserpass/browserpass-extension/commit/5e31b0d4d5233d633b4d578eb96e0eb18ede37c2.

@erayd what do you think?

**Comment by erayd** [comment] 2019-10-19 21:35
@vollkorn1982 We have discussed this further, and have come to the conclusion that the status quo is preferable. Putting path separators in a filename is extremely non-portable (even if technically legal), and considerably increases the potential for accidental bugs in our path-handling logic.

We won't be changing this for you, sorry.

**Closed by erayd** 2019-10-19 21:35 UTC
