### ISSUE TITLE
brave disables browserpass extension

### ISSUE THREAD

**Issue by jamincollins** [browserpass/browserpass-extension#168] opened 2019-09-19 02:07 UTC
### General information

-   Operating system + version: Arch Linux (fully up to date)
-   Browser + version: Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) unknown (64-bit)
-   Information about the host app:
    -   How did you install it? Installed via package manager
    -   If installed an official release, put a version (`$ browserpass --version`): Browserpass host app version: 3.0.6
-   Information about the browser extension:
    -   How did you install it? Installed via a package manager
    -   Browserpass extension version as reported by your browser: 3.1.1

---

### Exact steps to reproduce the problem

1. Install the packages (browserpass and brave) under Arch

2. Open browser

### What should happen?

Plugin is functional and available.

### What happened instead?

Brave refuses to enable the plugin and directs users to this link for more info:
https://support.brave.com/hc/en-us/articles/360017914832-Why-am-I-seeing-the-message-extensions-disabled-by-Brave-?hl=en-US

**Comment by maximbaz** [comment] 2019-09-19 06:41
hey, thanks for reporting! I'm tracking this bug on their side since it's clearly their regression and there's nothing I can do in the extension to fix this. 

https://github.com/brave/brave-browser/issues/5761

**Comment by kakolisgay** [comment] 2019-09-19 09:11
This issue is because of an upstream change with chromium, there's nothing extension developers can do. I'd suggest adding a comment to the brave issue to try to attract some more attention to it

**Comment by maximbaz** [comment] 2019-09-20 18:00
Closing as non-actionable for us

**Closed by maximbaz** 2019-09-20 18:00 UTC

**Comment by paulodiovani** [comment] 2019-10-11 20:17
Note: Installing the extensions from web store works.
